### ISSUE TITLE
CSX todo list (partial)

### ISSUE THREAD

**Issue by cmazzoli** [NSLS-II/Bug-Reports#26]
As discussed with Dan:
- [x] fCCD live (at least counters for total intensity and a couple of ROIs);
- [ ] Count_time problem with the fCCD camera;
- [ ] live check on data (written to disk?), reverse lookup from scan_id to file name;
- [x] cleanup (deconfig) not performed on abort and hanging on resume;
- [ ] RL libraries, scans, trajectories, meshes and coverage of the detector (existing to be implemented).

**Comment by danielballan** [comment]
@cmazzoli I'd like to check up on the progress on this list of items.

> - fCCD live (at least counters for total intensity and a couple of ROIs);

What does "live" mean here?

> - Count_time problem with the fCCD camera;

This is still a known issue.

> - live check on data (written to disk?), reverse lookup from scan_id to file name;

We have deployed this at XPD. We'll add it at CSX at our next visit.

> - cleanup (deconfig) not performed on abort and hanging on resume

I believe this has been fixed in the release you got yesterday. Please speak up if it happens again.

> - RL libraries, scans, trajectories, meshes and coverage of the detector (existing to be implemented).

Can you elaborate on this? If we discussed it in person, forgive me for not remembering what it means.

**Comment by tacaswell** [comment]
@cmazzoli What do you mean for 'RL libraries' ?

Can you elaborate on the count time issue?

**Comment by klauer** [comment]
Please open separate issues with more details if anything still remains from this list.
